services:
  api:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_PORT:-443}:443"
    volumes:
      - .:/app
    depends_on:
      - mailpit
    networks:
      - default

networks:
  default:

